name: Release
on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build Desktop
        run: ./gradlew createDistributable

      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: App
          path: |
            build/app-android.apk
            build/app-desktop.jar