name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 14

      - name: Build Java Application
        run: ./gradlew createDistributable

      - name: Package Desktop Application
        run: |
          jpackage \
            --name MDEditor \
            --input /desktop/build/compose \
            --main-jar desktop/build/libs/desktop-jvm-1.0-SNAPSHOT.jar \
            --main-class com.multiplatformcomposeapplication.Main.kt \
            --app-version 1.0.0 \
            --type exe
          cp MDEditor.exe /desktop/release/mdeditor-installer.exe  # Copy the generated installer to a known location

      - name: Upload Installer
        uses: actions/upload-artifact@v2
        with:
          name: your-app-installer
          path: /desktop/release/mdeditor-installer.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            /desktop/release/mdeditor-installer.exe
          token: ${{ secrets.GITHUB_TOKEN }}
