name: Release
on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build Android
        run: ./gradlew assembleAndroidRelease

      - name: Build Desktop
        run: ./gradlew assembleDesktopRelease

      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: App
          path: |
            build/app-android.apk
            build/app-desktop.jar

  deploy:

    needs: build
    
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Download Artifacts
        uses: actions/download-artifact@v1
        with:
          name: App

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: |
            app-android.apk
            app-desktop.jar
          asset_name: |
            app-android.apk
            app-desktop.jar
          asset_content_type: |
            application/vnd.android.package-archive
            application/java-archive