name: Build and Package Desktop App

on:
  push:
    branches:
      - master

jobs:
  build-and-package:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17  # Use the appropriate JDK version

      - name: Build Compose Multiplatform Project
        run: |
          # Replace with your actual build command for the Compose Multiplatform project
          ./gradlew createDistributable

#      - name: Package Desktop App for Windows
#        run: |
#          # Replace with the commands to package the Compose app for Windows using a tool like 'jpackage'
#          # Ensure that you specify the input, output, and other necessary parameters
#          jpackage \
#            --name MDEditor \
#            --input desktop/build/compose \
#            --main-jar desktop/build/libs/desktop-jvm-1.0-SNAPSHOT.jar \
#            --main-class com.multiplatformcomposeapplication.Main.kt \
#            --app-version 1.0.0 \
#            --type dmg

#      - name: Package Desktop App for macOS
#        run: |
#          # Replace with the commands to package the Compose app for macOS
#          # Make sure to specify the appropriate parameters for the macOS packaging tool you are using

      - name: Upload Installer
        uses: actions/upload-artifact@v2
        with:
          name: your-app-installer
          path: /home/runner/work/handson-kotlin-multiplatform-md-editor/handson-kotlin-multiplatform-md-editor/desktop/build/compose/binaries/main/app/MD Editor  # Adjust the path and file name accordingly

#      - name: Create GitHub Release
#        uses: actions/create-release@v1
#        with:
#          tag_name: v1.0.0
#          files: |
#           /home/runner/work/handson-kotlin-multiplatform-md-editor/handson-kotlin-multiplatform-md-editor/desktop/build/compose/binaries/main/app/home/runner/work/handson-kotlin-multiplatform-md-editor/handson-kotlin-multiplatform-md-editor/desktop/build/compose/binaries/main/app/MD Editor  # Adjust the path and file name
#          token: ${{ secrets.GITHUB_TOKEN }}
