package com.multiplatformcomposeapplication.common.ui.theme

import androidx.compose.ui.graphics.Color
 
public val Blue400 : Color = Color(0xFF4572E8)

public val md_theme_light_primary : Color = Color(0xFF2156CB)
public val md_theme_light_onPrimary : Color = Color(0xFFFFFFFF)
public val md_theme_light_primaryContainer : Color = Color(0xFFDBE1FF)
public val md_theme_light_onPrimaryContainer : Color = Color(0xFF00174B)
public val md_theme_light_secondary : Color = Color(0xFFB90063)
public val md_theme_light_onSecondary : Color = Color(0xFFFFFFFF)
public val md_theme_light_secondaryContainer : Color = Color(0xFFFFD9E2)
public val md_theme_light_onSecondaryContainer : Color = Color(0xFF3E001D)
public val md_theme_light_tertiary : Color = Color(0xFF745470)
public val md_theme_light_onTertiary : Color = Color(0xFFFFFFFF)
public val md_theme_light_tertiaryContainer : Color = Color(0xFFFFD6F8)
public val md_theme_light_onTertiaryContainer : Color = Color(0xFF2B122B)
public val md_theme_light_error : Color = Color(0xFFBA1A1A)
public val md_theme_light_errorContainer : Color = Color(0xFFFFDAD6)
public val md_theme_light_onError : Color = Color(0xFFFFFFFF)
public val md_theme_light_onErrorContainer : Color = Color(0xFF410002)
public val md_theme_light_background : Color = Color(0xFFFEFBFF)
public val md_theme_light_onBackground : Color = Color(0xFF1B1B1F)
public val md_theme_light_surface : Color = Color(0xFFFEFBFF)
public val md_theme_light_onSurface : Color = Color(0xFF1B1B1F)
public val md_theme_light_surfaceVariant : Color = Color(0xFFE2E2EC)
public val md_theme_light_onSurfaceVariant : Color = Color(0xFF45464F)
public val md_theme_light_outline : Color = Color(0xFF757680)
public val md_theme_light_inverseOnSurface : Color = Color(0xFFF2F0F4)
public val md_theme_light_inverseSurface : Color = Color(0xFF303034)
public val md_theme_light_inversePrimary : Color = Color(0xFFB4C5FF)
public val md_theme_light_shadow : Color = Color(0xFF000000)
public val md_theme_light_surfaceTint : Color = Color(0xFF2156CB)
public val md_theme_light_outlineVariant : Color = Color(0xFFC5C6D0)
public val md_theme_light_scrim : Color = Color(0xFF000000)

public val md_theme_dark_primary : Color = Color(0xFFB4C5FF)
public val md_theme_dark_onPrimary : Color = Color(0xFF002A78)
public val md_theme_dark_primaryContainer : Color = Color(0xFF003EA8)
public val md_theme_dark_onPrimaryContainer : Color = Color(0xFFDBE1FF)
public val md_theme_dark_secondary : Color = Color(0xFFFFB1C8)
public val md_theme_dark_onSecondary : Color = Color(0xFF650033)
public val md_theme_dark_secondaryContainer : Color = Color(0xFF8E004A)
public val md_theme_dark_onSecondaryContainer : Color = Color(0xFFFFD9E2)
public val md_theme_dark_tertiary : Color = Color(0xFFE2BBDB)
public val md_theme_dark_onTertiary : Color = Color(0xFF422741)
public val md_theme_dark_tertiaryContainer : Color = Color(0xFF5A3D58)
public val md_theme_dark_onTertiaryContainer : Color = Color(0xFFFFD6F8)
public val md_theme_dark_error : Color = Color(0xFFFFB4AB)
public val md_theme_dark_errorContainer : Color = Color(0xFF93000A)
public val md_theme_dark_onError : Color = Color(0xFF690005)
public val md_theme_dark_onErrorContainer : Color = Color(0xFFFFDAD6)
public val md_theme_dark_background : Color = Color(0xFF1B1B1F)
public val md_theme_dark_onBackground : Color = Color(0xFFE4E2E6)
public val md_theme_dark_surface : Color = Color(0xFF1B1B1F)
public val md_theme_dark_onSurface : Color = Color(0xFFE4E2E6)
public val md_theme_dark_surfaceVariant : Color = Color(0xFF45464F)
public val md_theme_dark_onSurfaceVariant : Color = Color(0xFFC5C6D0)
public val md_theme_dark_outline : Color = Color(0xFF8F909A)
public val md_theme_dark_inverseOnSurface : Color = Color(0xFF1B1B1F)
public val md_theme_dark_inverseSurface : Color = Color(0xFFE4E2E6)
public val md_theme_dark_inversePrimary : Color = Color(0xFF2156CB)
public val md_theme_dark_shadow : Color = Color(0xFF000000)
public val md_theme_dark_surfaceTint : Color = Color(0xFFB4C5FF)
public val md_theme_dark_outlineVariant : Color = Color(0xFF45464F)
public val md_theme_dark_scrim : Color = Color(0xFF000000)


public val seed : Color = Color(0xFF4572E8)